spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: murali27#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
